# Generated by Django 4.1.1 on 2022-09-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_member_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
