# Generated by Django 4.1.1 on 2022-09-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_member_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='snippet',
            field=models.CharField(default='dhgch', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
