# Generated by Django 4.1.1 on 2022-09-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_member_snippet_alter_member_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='snippet',
            field=models.CharField(max_length=100),
        ),
    ]
